# Generated by Django 4.0.3 on 2022-03-20 22:34

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('phone', models.CharField(max_length=30, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('credit_card', django_cryptography.fields.encrypt(models.CharField(max_length=20, null=True))),
                ('last_four_card_numbers', models.CharField(max_length=20, null=True)),
                ('franchise', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='csvFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='csvfiles/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('on_hold', models.BooleanField(default=False)),
                ('processing', models.BooleanField(default=False)),
                ('failed', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
    ]
