# Generated by Django 4.0.3 on 2022-03-20 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_importer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='on_hold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='processing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
