# Generated by Django 4.0.3 on 2022-03-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_importer', '0004_contact_last_four_card_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='credit_card',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='franchise',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_four_card_numbers',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
