# Generated by Django 4.0.3 on 2022-03-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_importer', '0005_alter_contact_credit_card_alter_contact_franchise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='last_four_card_numbers',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
