# Generated by Django 4.0.3 on 2022-03-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_importer', '0006_alter_contact_last_four_card_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='franchise',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
