# Generated by Django 4.0.3 on 2022-03-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_importer', '0008_alter_contact_credit_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='failed',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='finished',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='on_hold',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='processing',
        ),
        migrations.AddField(
            model_name='csvfile',
            name='failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='csvfile',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='csvfile',
            name='on_hold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='csvfile',
            name='processing',
            field=models.BooleanField(default=False),
        ),
    ]
