# Generated by Django 4.0.3 on 2022-03-20 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csv_importer', '0009_remove_contact_failed_remove_contact_finished_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-id']},
        ),
    ]
